[tool.poetry]
name = "slicer"
version = "0.1.0"
description = ""
authors = ["Raini Wu <rainiwu@ucsd.edu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
